name: LLM Review
on: [pull_request]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: pritom007/ai-pr-review@v1
        with:
          api-key: ${{ API_KEY }}
          model-name: "deepseek-chat"
          base-url: "https://api.deepseek.com/v1"
          temperature: "0.7"
          max-tokens: "10000"
          language: "Chinese"
